### ISSUE TITLE
Allow branch creating or handle differently environment variables

### ISSUE THREAD

**Issue by websoftwares** [OpenSTFoundation/ost-sdk-php#12]
I wanted to submit a PR from a fork as I can not create branches from develop or master (permission)
But as the tests require the environment files being parsed, the PR keeps failing as the encrypted environment files are not used.

Maybe get rid of the dependency of testing the API and use mock responses instead?

More information found here:

Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions

**Comment by puneet-khushwani-eth** [comment]
Hi

We had merged https://github.com/OpenSTFoundation/ost-sdk-php/pull/13 earlier this month which took care of running test cases used .env file.

However, we have made some changes to it and would release it with our upcoming release.
